### ISSUE TITLE
sudo make install overwrites /usr/local/bin folder

### ISSUE THREAD

**Issue by racecannon5976** [lavoiesl/osx-cpu-temp#10]
I'm running MacOS 10.12.2. I don't know if there already existed a /usr/local/bin folder, but after compiling your program, I ran "sudo make install" and then listed the contents of /usr/local/bin and was informed it was not a folder, but an executable file. So I ran it and it was the temperature program. I renamed it to osx-cpu-temp, then created a new /usr/local/bin directory, then moved it in there. It works fine now but I'm afraid the "sudo make install" command might have overwritten /usr/local/bin with your program. You might want to check on this. Thank you for the program.

**Comment by lavoiesl** [comment]
Thanks for the report.
