### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by gwerbin** [lavoiesl/osx-cpu-temp#9]
Hey there,

I wrote a Homebrew formula for your program, in case someone doesn't want to use CLibs.

You can access it with:

```
brew tap gwerbin/homebrew-tap
brew install osx-cpu-temp
```

I wrote it for personal use, but if you're interested I can make a PR to the Hombrew team. Tagging a release (even if it's a meaningless 0.1.0 or 1.0.0) would help, so it doesn't get relegated to the HEAD-only tap.

**Comment by lavoiesl** [comment]
Sure thing, I created https://github.com/lavoiesl/osx-cpu-temp/releases/tag/1.0.0
Thanks.
